- name: Install Neovim
  hosts: localhost
  tasks:
    - name: clone neovim
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/Desktop/neovim"
        single_branch: yes
        version: v0.10.1
    - name: Install a list of Homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - cmake
        - gettext
        - ninja
        - luajit
    - name: neovim
      make:
        chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/Desktop/neovim"
        params:
          CMAKE_BUILD_TYPE: "RelWithDebInfo"
    - name: install neovim
      become: true
      make:
        chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/Desktop/neovim"
        target: install
