#!/usr/bin/env bash


git clone git@github.com:neovim/neovim.git ~/personal/neovim
cd ~/personal/neovim
git fetch
git checkout v0.10.2

brew install cmake gettext luajit ninja
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install


# to remove
# sudo rm -f /usr/local/bin/nvim && sudo rm -rf /usr/local/share/nvim && sudo rm -rf /usr/local/lib/nvim